$(document).ready(
    function(){
        $("#").submit(
            function(event){
                event.preventDefault();
                Console.log($("#").val());
            }
        );
    }
);